import { Montserrat } from 'next/font/google'
import "./globals.css";
import Navbar from '@/components/Navbar';
import GetInTouch from '@/components/GetInTouch';
import Footer from '@/components/Footer';

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: "Personal Web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Navbar/>
      <body className={montserrat.className}>{children}</body>
      <GetInTouch/>
      <Footer/>
    </html>
  );
}
